# Frames colors
YELLOW_BACKGROUND = '#fff1c8'
PINK_BACKGROUND = '#ffcccc'
GREEN_BACKGROUND = '#d7e4d1'
SWAMP_FOREGROUND = '#e2f7b5'
ORANGE_FOREGROUND = '#ffd38f'
NEW_USER_WINDOW_FOREGROUND = '#d3e4ef'

# Button colors
PINK_FOREGROUND = '#d07979'
CRIMSON_HOVER = '#92465f'
BEGIN_BUTTON_FOREGROUND_COLOR = '#d1ff00'
BEGIN_BUTTON_HOVER_COLOR = '#ffec00'
SOUNDS_BUTTONS_FOREGROUND = '#333f65'
SOUNDS_BUTTONS_HOVER = '#232e52'
POSITIVE_BUTTON_FOREGROUND = '#578555'
POSITIVE_BUTTON_HOVER = '#2d642a'
NEGATIVE_BUTTON_FOREGROUND = '#ac1416'
NEGATIVE_BUTTON_HOVER = '#ce6163'
ANSWER_BUTTON_FOREGROUND = '#c1461e'
ANSWER_BUTTON_HOVER = '#ff662a'

# Checkboxes colors
CHECKBOX_HOVER_COLOR = '#68a248'

# Progress bars colors
PROGRESS_FOREGROUND = '#e6ffda'
PROGRESS_COLOR = '#55e400'

# Question tree colors
GREEN = '#b6d7a8'
RED = '#fea5aa'
WHITE = '#ffffff'

# Error colors
ERROR_COLOR = '#d3e4ef'
SUCCESS_COLOR = '#9effa2'

# Canvas colors
PDF_OUTPUT_COLOR = '#ECE8F3'
